Web/WMIP.Web/Controllers/AlbumsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WMIP.Constants;
using WMIP.Data.Models;
using WMIP.Services.Contracts;
using WMIP.Web.Models.Albums;

namespace WMIP.Web.Controllers
{
    public class AlbumsController : Controller
    {
        private readonly IAlbumsService albumsService;
        private readonly IMapper mapper;

        public AlbumsController(IAlbumsService albumsService, IMapper mapper)
        {
            this.albumsService = albumsService;
            this.mapper = mapper;
        }

        public IActionResult All()
        {
            return this.View();
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                this.TempData["Error"] = string.Format(GenericMessages.CouldntDoSomething, "find album");
                return this.RedirectToAction("Index", "Home");
            }

            var userIsCreator = this.albumsService.IsUserCreatorByName(this.User.Identity.Name, id.Value);

            Album album = null;

            if (userIsCreator)
            {
                album = this.albumsService.GetById(id.Value);
                if (album == null)
                {
                    this.TempData["Error"] = string.Format(GenericMessages.CouldntDoSomething, "find album");
                    return this.RedirectToAction("Index", "Home");
                }
                var model = this.mapper.Map<AlbumDetailsCreatorViewModel>(album);
                return this.View(model);
            }
            else
            {
                album = this.albumsService.GetNotSecretById(id.Value);
                if (album == null)
                {
                    this.TempData["Error"] = string.Format(GenericMessages.CouldntDoSomething, "find album");
                    return this.RedirectToAction("Index", "Home");
                }
                var model = this.mapper.Map<AlbumDetailsViewModel>(album);
                return this.View(model);
            }
        }
    }
}

Web/WMIP.Web/Controllers/RatingsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WMIP.Services.Contracts;
using WMIP.Web.Models.Rating;

namespace WMIP.Web.Controllers
{
    public class RatingsController : Controller
    {
        private readonly IRatingsService ratingsService;
        private readonly IUsersService usersService;
        private readonly IMapper mapper;

        public RatingsController(IRatingsService ratingsService, IUsersService usersService, IMapper mapper)
        {
            this.ratingsService = ratingsService;
            this.usersService = usersService;
            this.mapper = mapper;
        }

        [HttpPost]
        public IActionResult Rate([FromBody]RatingViewModel model)
        {
            var userId = this.usersService.GetIdFromUsername(this.User.Identity.Name);

            var newScore = this.ratingsService.Rate(model.PostId, userId, model.RatingType);

            return this.Json(new { newScore });
        }

        public IActionResult My()
        {
            var usersRatings = this.ratingsService.GetUsersRatings(this.User.Identity.Name);
            var mappedRatings = this.mapper.Map<IEnumerable<MyRatingViewModel>>(usersRatings);
            return this.View(mappedRatings);
        }
    }
}

Web/WMIP.Web/Controllers/SongsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WMIP.Constants;
using WMIP.Data.Models;
using WMIP.Services.Contracts;
using WMIP.Web.Models.Songs;

namespace WMIP.Web.Controllers
{
    public class SongsController : Controller
    {
        private readonly ISongsService songsService;
        private readonly IMapper mapper;

        public SongsController(ISongsService songsService, IMapper mapper)
        {
            this.songsService = songsService;
            this.mapper = mapper;
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                this.TempData["Error"] = string.Format(GenericMessages.CouldntDoSomething, "find song");
                return this.RedirectToAction("Index", "Home");
            }

            var userIsCreator = this.songsService.IsUserCreatorByName(this.User.Identity.Name, id.Value);

            Song song = null;
            if (userIsCreator)
            {
                song = this.songsService.GetById(id.Value);
                if (song == null)
                {
                    this.TempData["Error"] = string.Format(GenericMessages.CouldntDoSomething, "find song");
                    return this.RedirectToAction("Index", "Home");
                }
                var model = this.mapper.Map<SongDetailsCreatorViewModel>(song);
                return this.View(model);
            }
            else
            {
                song = this.songsService.GetNotSecretById(id.Value);
                if (song == null)
                {
                    this.TempData["Error"] = string.Format(GenericMessages.CouldntDoSomething, "find song");
                    return this.RedirectToAction("Index", "Home");
                }
                var model = this.mapper.Map<SongDetailsViewModel>(song);
                return this.View(model);
            }
        }
    }
}

Web/WMIP.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WMIP.Data.Models;
using WMIP.Services.Contracts;
using WMIP.Web.Models.Users;

namespace WMIP.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUsersService userService;
        private readonly SignInManager<User> signInManager;
        private readonly UserManager<User> userManager;
        private readonly IMapper mapper;

        public UsersController(IUsersService userService, UserManager<User> userManager, SignInManager<User> signInManager, IMapper mapper)
        {
            this.userService = userService;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.mapper = mapper;
        }
        public IActionResult Register()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel model)
        {
            var a = this.ModelState.ValidationState;
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var isRegister = this.userService.Register(model.Username, model.Password, model.Email).GetAwaiter().GetResult();

            if (!isRegister)
            {
                return this.View();
            }

            return this.RedirectToAction("Index", "Home");
        }

        public IActionResult Login()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var isLogin = this.userService.Login(model.Username, model.Password, model.RememberMe);

            if (!isLogin)
            {
                this.ModelState.AddModelError("Username", "Username and password do not match");
                return this.View();
            }

            return this.RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Logout()
        {
            this.userService.Logout();
            return this.RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return this.View();
        }
    }
}

Web/WMIP.Web/Views/Shared/AdminNavigation.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Admininstration
        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Management">User Management</a>
        <a class="dropdown-item" asp-area="Admin" asp-controller="Approval" asp-action="All">Approval Management</a>
        <a class="dropdown-item" asp-area="Admin" asp-controller="Articles" asp-action="Management">Articles Management</a>
        <a class="dropdown-item" asp-area="Admin" asp-controller="Articles" asp-action="Create">New Article</a>
    </div>
</li>

Web/WMIP.Web/Views/Shared/ArtistNavigation.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Artist
        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" asp-area="Artist" asp-controller="Songs" asp-action="My">My Songs</a>
        <a class="dropdown-item" asp-area="Artist" asp-controller="Albums" asp-action="My">My Albums</a>
        <a class="dropdown-item" asp-area="Artist" asp-controller="Songs" asp-action="Create">New Song</a>
        <a class="dropdown-item" asp-area="Artist" asp-controller="Albums" asp-action="Create">New Album</a>
        <a class="dropdown-item" asp-area="Artist" asp-controller="Approval" asp-action="MyRequests">My Approval Requests</a>
    </div>
</li>

Web/WMIP.Web/Views/Shared/CommentDisplayPartial.cshtml
@model CommentDisplayViewModel

<div class="commentParent">
    <div class="commentHeader">
        @{ ViewData["UseHorizontal"] = true; }
        <partial name="RatingPartial" model="new RatingViewModel { PostId = Model.Id, Score = Model.Score, RatingType = Model.CurrentUserRating }" />
        <div class="col-md-11">
            <h6><b>@Model.Title</b>, by @Model.AuthorName, submitted on: @Model.CreatedOn.ToShortDateString(), @Model.CreatedOn.ToShortTimeString()</h6>
            <span title="Hide" class="hideComment">-</span>
        </div>
        <div class="row">
            @Html.Partial("NewCommentPartial", new NewCommentViewModel { PostId = Model.Id, Type = "reply" })
        </div>
    </div>
    <div class="commentBody">
        <p>@Html.Raw(Model.Body)</p>
        <div class="newCommentsContainer"></div>
        @if (Model.Replies != null && Model.Replies.Count() > 0)
        {
            <div class="commentReply">
                @foreach (var reply in Model.Replies)
                {
                    @Html.Partial("CommentDisplayPartial", reply)
                }
            </div>
        }
    </div>
</div>

<script src="~/js/hide-comment.js"></script>

Web/WMIP.Web/Views/Shared/LoggedInNavigation.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        My
        <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" asp-area="" asp-controller="Reviews" asp-action="My">My Reviews</a>
        <a class="dropdown-item" asp-area="" asp-controller="Comments" asp-action="My">My Comments</a>
        <a class="dropdown-item" asp-area="" asp-controller="Ratings" asp-action="My">My Ratings</a>
    </div>
</li>

Web/WMIP.Web/Views/Shared/NewCommentPartial.cshtml
@model NewCommentViewModel

@{
    Layout = null;
}

@if (this.User.Identity.IsAuthenticated)
{
    <div class="col-md-12">
        <a class="btn btn-primary newCommentButton">Write a @Model.Type</a>
        <div class="newCommentsContainer"></div>

        <div class="col-md-12 formPopup newCommentForm">
            <form class="mx-auto w50" asp-controller="Comments" asp-action="Create" data-ajax-complete="onCommentComplete" data-ajax-failure="onCommentFail" data-ajax="true" data-ajax-method="POST">
                <input asp-for="Username" value="@User.Identity.Name" type="hidden" />
                <input asp-for="PostId" type="hidden" />
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="Title"></label>
                            <input asp-for="Title" class="form-control" placeholder="Title..." />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="Body"></label>
                            <textarea id="bodyEditor" asp-for="Body " class="form-control newCommentBody" placeholder="Body..."></textarea>
                            <span asp-validation-for="Body" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="button-holder d-flex justify-content-center">
                    <button type="submit" class="btn bg-info">Create</button>
                </div>
            </form>
        </div>
    </div>

    <script>
        tinymce.init({
            selector: '.newCommentBody'
        });
    </script>
    <script src="~/js/create-comment.js"></script>
}

Web/WMIP.Web/Views/Shared/RatingPartial.cshtml
@model RatingViewModel

@if (this.ViewData["UseHorizontal"] != null && this.ViewData["UseHorizontal"] as bool? == true)
{
    <form>
        <div class="col-md-1 col-sm-12 col-xs-12">
            <div class="min-100">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="diplay-inline" data-id="@Model.PostId" data-action="up">
                        <span class="@(Model.RatingType == WMIP.Data.Models.Enums.RatingType.Positive ? "upvote-color" : string.Empty) glyphicon glyphicon-chevron-up mouse-pointer"></span>
                    </div>
                }
                <div class="diplay-inline" data-id="@Model.PostId" data-action="ratingsCount">@Model.Score</div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="diplay-inline" data-id="@Model.PostId" data-action="down">
                        <span class="@(Model.RatingType == WMIP.Data.Models.Enums.RatingType.Negative ? "downvote-color" : string.Empty) glyphicon glyphicon-chevron-down mouse-pointer"></span>
                    </div>
                }
            </div>
        </div>
    </form>
}
else
{
    <form>
        <div class="col-md-1 col-sm-1 col-xs-1">
            <div class="text-center">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="row" data-id="@Model.PostId" data-action="up">
                        <span class="@(Model.RatingType == WMIP.Data.Models.Enums.RatingType.Positive ? "upvote-color" : string.Empty) glyphicon glyphicon-chevron-up mouse-pointer"></span>
                    </div>
                }
                <div class="row" data-id="@Model.PostId" data-action="ratingsCount">@Model.Score</div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="row" data-id="@Model.PostId" data-action="down">
                        <span class="@(Model.RatingType == WMIP.Data.Models.Enums.RatingType.Negative ? "downvote-color" : string.Empty) glyphicon glyphicon-chevron-down mouse-pointer"></span>
                    </div>
                }
            </div>
        </div>
    </form>
}

<script src="~/js/rating-script.js"></script>

Web/WMIP.Web/Views/Shared/SearchPartial.cshtml
<div class="row">
    <div class="col-md-4">
        <input id="searchBar" type="search" class="form-control searchbar" placeholder="Search..." />

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 searchResults" id="resultsBox">
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/get-search-results.js"></script>

Web/WMIP.Web/Views/Shared/SearchResultsPartial.cshtml
@model IEnumerable<WMIP.Services.Dtos.Search.SearchResultDto>

@if (Model != null && Model.Count() > 0)
{
    <div class="row">
        <div class="col-md-12">
            <span class="glyphicon glyphicon-remove float-right collapse-icon"></span>
        </div>
    </div> 
    @foreach (var result in Model)
    {
        <div class="row">
            <div class="col-md-12">
                <div class="link-container">
                    <a class="float-left fixed-size-link" href="/@(result.SearchResultType)s/Details/@result.Id">@result.Title</a>
                    <p class="float-right mbottom0">@result.SearchResultType</p>
                </div>
            </div>
        </div>
    }
}
else
{
    <p class="text-danger">No results found.</p>
}

Web/WMIP.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/unobtrusiveajax.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" type="image/png" href="~/favicon.ico" />

    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top abolute-important">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Web Music Info Place</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Articles" asp-action="All">All Articles</a></li>
                    @if (this.User != null && this.User.Identity.IsAuthenticated)
                    {
                        Html.RenderPartial("LoggedInNavigation");
                    }
                    @if (this.User != null && this.User.IsInRole("Admin"))
                    {
                        Html.RenderPartial("AdminNavigation");
                    }

                    @if (this.User != null && this.User.IsInRole("Artist"))
                    {
                        Html.RenderPartial("ArtistNavigation");
                    }
                </ul>
                @Html.Partial("_LoginPartial")
                @Html.Partial("SearchPartial")
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Web Music Info Place</p>
        </footer>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />
    <script>
        toastr.options.positionClass = "toast-bottom-center";

        $(document).ready(function () {
            if('@TempData["Error"]'){
                toastr.error('@TempData["Error"]');
            }
            if('@TempData["Success"]'){
                toastr.success('@TempData["Success"]');
            }
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>